### ISSUE TITLE
Feat: Make initialising graph easier

### ISSUE THREAD

**Issue by eng-tsmith** [jnurkka/bubbleSequencer#23]
US: We want to make initialising any graph easy based on any process data

UAT:
- graph can be initialised from a CSV
- optional: graph can be initialised from mermaid

**Comment by jnurkka** [comment]
@eng-tsmith do you know Mermaid? We could also use mermaid code syntax, that would be easier to model

For example this is Mermaid for our current test graph:

![image](https://github.com/jnurkka/bubbleSequencer/assets/9248327/6a933005-2185-45d9-9221-ba670b547fd8)

**Comment by eng-tsmith** [comment]
@jnurkka schaut gut aus. der input in unsrem code schaut sehr ähnlich aus:
// Set edges
graph.addEdge(0, 1, 1.0f);
graph.addEdge(0, 2, 1.0f);
graph.addEdge(1, 2, 1.0f);
graph.addEdge(2, 3, 1.0f);
graph.addEdge(2, 4, 1.0f);
graph.addEdge(3, 5, 1.0f);
graph.addEdge(3, 6, 1.0f);
graph.addEdge(3, 8, 1.0f);
graph.addEdge(4, 6, 1.0f);
graph.addEdge(5, 5, 1.0f);
graph.addEdge(5, 7, 1.0f);
graph.addEdge(6, 7, 1.0f);
graph.addEdge(6, 8, 1.0f);


aber um den graph dann im memory zu haben würde ich bei der adjacency matrix bleiben. hab da bissl research gemacht und scheint für unseren use-case gut geeignet zu sein

**Comment by eng-tsmith** [comment]
still relevant?
